[project]
name = "cert-to-access-web-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "gunicorn>=23.0.0",
]
